#!/usr/bin/env bun

import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parse } from 'yaml';
import {
  buildCategoryKey,
  CategoryRegistry,
  type CategoryNode,
} from '../../packages/rules/src/index.js';
import { MERCHANT_KEYWORDS } from '../../packages/core/src/categorizer/keywords.js';
import { LOCATION_KEYWORDS } from '../../packages/core/src/categorizer/keywords-locations.js';
import { ENGLISH_KEYWORDS } from '../../packages/core/src/categorizer/keywords-english.js';
import { NICHE_KEYWORDS } from '../../packages/core/src/categorizer/keywords-niche.js';

const ROOT = resolve(import.meta.dir, '../..');
const OUTPUT = resolve(
  ROOT,
  'packages/core/src/categorizer/keyword-overrides.ts',
);
const WRITE = process.argv.includes('--write');

const LEGACY_CATEGORY_ALIASES: Readonly<Record<string, string>> = {
  'dining.bar': 'dining.restaurant',
  'travel.accommodation': 'travel.hotel',
  'travel.flight': 'travel.airline',
};

const sources = [
  { name: 'base', values: MERCHANT_KEYWORDS },
  { name: 'locations', values: LOCATION_KEYWORDS },
  { name: 'english', values: ENGLISH_KEYWORDS },
  { name: 'niche', values: NICHE_KEYWORDS },
] as const;

const categories = parse(
  await readFile(resolve(ROOT, 'packages/rules/data/categories.yaml'), 'utf8'),
) as { categories: CategoryNode[] };
const registry = new CategoryRegistry(categories.categories);

interface Definition {
  category: string;
  canonicalSpelling: boolean;
}

const allCategories = new Map<string, Set<string>>();
const historicallySelected = new Map<string, Definition>();

for (const source of sources) {
  for (const [authoredKeyword, authoredCategory] of Object.entries(
    source.values,
  )) {
    const keyword = authoredKeyword.trim().toLowerCase();
    if (!keyword) continue;
    const token =
      LEGACY_CATEGORY_ALIASES[authoredCategory] ?? authoredCategory;
    const resolution = registry.resolve(token, {
      allowBareLeaf: true,
      allowWildcard: false,
    });
    if (!resolution.value) {
      throw new Error(
        `${source.name}:${authoredKeyword} has invalid category ${authoredCategory}`,
      );
    }
    const category = buildCategoryKey(
      resolution.value.category,
      resolution.value.subcategory,
    );
    const definitions = allCategories.get(keyword) ?? new Set<string>();
    definitions.add(category);
    allCategories.set(keyword, definitions);

    const canonicalSpelling = authoredKeyword.trim() === keyword;
    const previous = historicallySelected.get(keyword);
    if (previous?.canonicalSpelling && !canonicalSpelling) continue;
    historicallySelected.set(keyword, { category, canonicalSpelling });
  }
}

const decisions = [...allCategories]
  .filter(([, values]) => values.size > 1)
  .map(([keyword, values]) => {
    const selected = historicallySelected.get(keyword)?.category;
    if (!selected || !values.has(selected)) {
      throw new Error(`No historical selection for conflict "${keyword}"`);
    }
    return [keyword, selected] as const;
  })
  .sort(([left], [right]) => left.localeCompare(right));

const lines = decisions.map(
  ([keyword, category]) =>
    `  ${JSON.stringify(keyword)}: ${JSON.stringify(category)},`,
);
const output = `/**
 * Explicit decisions for every keyword that has multiple canonical mappings.
 *
 * Generated by scripts/migrations/generate-keyword-overrides.ts. Review this
 * file when a keyword source changes; matcher construction fails when a new
 * conflict has no entry or an entry no longer names one of its candidates.
 */
export const EXPLICIT_KEYWORD_OVERRIDES: Readonly<Record<string, string>> = {
${lines.join('\n')}
};
`;

let current = '';
try {
  current = await readFile(OUTPUT, 'utf8');
} catch {
  // A missing generated contract is drift.
}

if (current === output) {
  console.log(`Keyword override contract is clean (${decisions.length} decisions).`);
} else if (WRITE) {
  await writeFile(OUTPUT, output, 'utf8');
  console.log(`Wrote ${decisions.length} explicit keyword decisions.`);
} else {
  console.error(
    `Keyword override contract drifted (${decisions.length} decisions); run with --write.`,
  );
  process.exitCode = 1;
}
