/**
 * Static map of English/uppercase merchant descriptor strings to canonical category IDs.
 * These match how Korean card billing systems encode merchant names in English/uppercase.
 * Category IDs follow the taxonomy defined in packages/rules/data/categories.yaml.
 * Higher-specificity matches take priority during lookup.
 */
export const ENGLISH_KEYWORDS: Record<string, string> = {

  // ── Section 1: Korean brands in UPPERCASE English ──

  // Cafe / Coffee
  'STARBUCKS COFFEE KOREA': 'dining.cafe',
  'STARBUCKS DT': 'dining.cafe',
  'STARBUCKS RESERVE': 'dining.cafe',
  'STARBUCKS R': 'dining.cafe',
  'STARBUCKS': 'dining.cafe',
  'EDIYA COFFEE': 'dining.cafe',
  'EDIYA COFFEE CO': 'dining.cafe',
  'EDIYA': 'dining.cafe',
  'MEGA MGC COFFEE': 'dining.cafe',
  'MEGA COFFEE': 'dining.cafe',
  'COMPOSE COFFEE': 'dining.cafe',
  'PAIK S COFFEE': 'dining.cafe',
  'PAIKS COFFEE': 'dining.cafe',
  'PAIK COFFEE': 'dining.cafe',
  'HOLLYS COFFEE': 'dining.cafe',
  'HOLLYS': 'dining.cafe',
  'PAUL BASSETT': 'dining.cafe',
  'A TWOSOME PLACE': 'dining.cafe',
  'TWOSOME PLACE': 'dining.cafe',
  'TWOSOME': 'dining.cafe',
  'COFFEE BEAN': 'dining.cafe',
  'THE COFFEE BEAN': 'dining.cafe',
  'COFFEE BEAN AND TEA': 'dining.cafe',
  'PASCUCCI': 'dining.cafe',
  'THE VENTI': 'dining.cafe',
  'CAFE BENE': 'dining.cafe',
  'TOM N TOMS': 'dining.cafe',
  'ANGEL IN US': 'dining.cafe',
  'BLUE BOTTLE': 'dining.cafe',
  'COFFEESMITH': 'dining.cafe',
  'MAMMOTH COFFEE': 'dining.cafe',
  'GONG CHA': 'dining.cafe',
  'GONGCHA': 'dining.cafe',
  'JUICY': 'dining.cafe',
  'AUNTIE ANNES': 'dining.cafe',
  'DALKOM COFFEE': 'dining.cafe',
  'DROPTOP': 'dining.cafe',
  'BEANBROTHERS': 'dining.cafe',
  'FRITZ COFFEE': 'dining.cafe',
  'FELT COFFEE': 'dining.cafe',
  'COFFEE LIBRE': 'dining.cafe',
  'TERAROSA': 'dining.cafe',
  'MOMOS COFFEE': 'dining.cafe',
  'SMOOTHIE KING': 'dining.cafe',
  'TIGER SUGAR': 'dining.cafe',
  'OSULLOC': 'dining.cafe',
  'O SULLOC': 'dining.cafe',
  'OSULLOC FARM': 'dining.cafe',
  '공차': 'dining.cafe',

  // Bakery / Ice Cream
  'PARIS BAGUETTE': 'dining.cafe',
  'PARIS BAGUETTE CO': 'dining.cafe',
  'SPC SAMLIP': 'dining.cafe',
  'SPC GROUP': 'dining.cafe',
  'TOUS LES JOURS': 'dining.cafe',
  'BASKIN ROBBINS KR': 'dining.cafe',
  'BASKIN ROBBINS KOREA': 'dining.cafe',
  'BASKIN ROBBINS': 'dining.cafe',
  'BR KOREA': 'dining.cafe',
  'DUNKIN DONUTS KR': 'dining.cafe',
  'DUNKIN KOREA': 'dining.cafe',
  'DUNKIN': 'dining.cafe',
  'KRISPY KREME KR': 'dining.cafe',
  'KRISPY KREME KOREA': 'dining.cafe',
  'KRISPY KREME': 'dining.cafe',
  'SULBING': 'dining.cafe',
  'MILKY WAY DESSERT': 'dining.cafe',
  'CAFE DE PARIS': 'dining.cafe',
  'CAFE COMMA': 'dining.cafe',

  // Fast Food
  'MCDONALD S KOREA': 'dining.fast_food',
  'MCDONALDS KR': 'dining.fast_food',
  'MCDONALDS KOREA': 'dining.fast_food',
  'MCDONALDS': 'dining.fast_food',
  'MC DONALDS': 'dining.fast_food',
  'BURGER KING KOREA': 'dining.fast_food',
  'BURGER KING KR': 'dining.fast_food',
  'BURGER KING': 'dining.fast_food',
  'LOTTERIA CO LTD': 'dining.fast_food',
  'LOTTERIA CO': 'dining.fast_food',
  'LOTTERIA': 'dining.fast_food',
  'MOM S TOUCH': 'dining.fast_food',
  'MOMSTOUCH CO': 'dining.fast_food',
  'MOMSTOUCH': 'dining.fast_food',
  'KFC KOREA': 'dining.fast_food',
  'KFC': 'dining.fast_food',
  'SUBWAY KOREA': 'dining.fast_food',
  'SUBWAY': 'dining.fast_food',
  'POPEYES KOREA': 'dining.fast_food',
  'POPEYES': 'dining.fast_food',
  'WENDYS KOREA': 'dining.fast_food',
  'WENDYS': 'dining.fast_food',
  'TACO BELL KOREA': 'dining.fast_food',
  'TACO BELL': 'dining.fast_food',
  'SHAKE SHACK': 'dining.fast_food',
  'FIVE GUYS KOREA': 'dining.fast_food',
  'FIVE GUYS': 'dining.fast_food',
  'NENE CHICKEN': 'dining.fast_food',
  'BB Q CHICKEN': 'dining.fast_food',
  'BBQ CHICKEN': 'dining.fast_food',
  'KYOCHON F B': 'dining.fast_food',
  'KYOCHON CHICKEN': 'dining.fast_food',
  'KYOCHON': 'dining.fast_food',
  'BHFC': 'dining.fast_food',
  'PELICANA CHICKEN': 'dining.fast_food',
  'GOOBNE CHICKEN': 'dining.fast_food',
  'HYUNDAI GREEN FOOD': 'dining.fast_food',
  'LOTTERIA DRIVE THRU': 'dining.fast_food',

  // Pizza / Delivery
  'DOMINO S PIZZA KR': 'dining.delivery',
  'DOMINOS PIZZA KOREA': 'dining.delivery',
  'DOMINOS': 'dining.delivery',
  'PIZZA HUT KOREA': 'dining.delivery',
  'PIZZA HUT': 'dining.delivery',
  'MR PIZZA': 'dining.delivery',
  'PIZZA SCHOOL': 'dining.delivery',
  'PIZZA MALL': 'dining.delivery',
  'BBQ CHICKEN CO': 'dining.delivery',
  'GENESIS BBQ': 'dining.delivery',
  'BAEDAL MINJOK': 'dining.delivery',
  'WOOWA BROTHERS': 'dining.delivery',
  'BAEMIN B MART': 'dining.delivery',
  'BAEMIN': 'dining.delivery',
  'YOGIYO CO': 'dining.delivery',
  'YOGIYO': 'dining.delivery',
  'COUPANG EATS': 'dining.delivery',

  // Restaurants
  'OUTBACK STEAKHOUSE KOREA': 'dining.restaurant',
  'OUTBACK KOREA': 'dining.restaurant',
  'OUTBACK': 'dining.restaurant',
  'VIPS KOREA': 'dining.restaurant',
  'VIPS': 'dining.restaurant',
  'ASHLEY QUEENS': 'dining.restaurant',
  'ASHLEY': 'dining.restaurant',
  'TGIF KOREA': 'dining.restaurant',
  'TGIF': 'dining.restaurant',
  'BENNIGANS KOREA': 'dining.restaurant',
  'CHILIS KOREA': 'dining.restaurant',
  'TOKIO RESTAURANT': 'dining.restaurant',
  'GENESIS BBQ KOREA': 'dining.restaurant',
  'COLD STONE CREAMERY': 'dining.cafe',
  'HAAGEN DAZS KOREA': 'dining.cafe',

  // Grocery / Supermarket
  'EMART INC': 'grocery.supermarket',
  'EMART CO LTD': 'grocery.supermarket',
  'EMART TRADERS': 'grocery.supermarket',
  'EMART EVERYDAY': 'grocery.supermarket',
  'SHINSEGAE EMART': 'grocery.supermarket',
  'HOMEPLUS CO LTD': 'grocery.supermarket',
  'HOMEPLUS CO': 'grocery.supermarket',
  'HOMEPLUS': 'grocery.supermarket',
  'LOTTE MART CO': 'grocery.supermarket',
  'LOTTE MART CO LTD': 'grocery.supermarket',
  'LOTTE MART': 'grocery.supermarket',
  'COSTCO WHOLESALE KR': 'grocery.supermarket',
  'COSTCO KOREA INC': 'grocery.supermarket',
  'COSTCO KOREA': 'grocery.supermarket',
  'COSTCO': 'grocery.supermarket',
  'GS THE FRESH': 'grocery.supermarket',
  'GS SUPERFRESH': 'grocery.supermarket',
  'LOTTESUPER': 'grocery.supermarket',
  'LOTTE SUPER': 'grocery.supermarket',
  'HANARO MART': 'grocery.supermarket',
  'NONGCHUP': 'grocery.supermarket',
  'MEGA MART': 'grocery.supermarket',
  'HOMEEVER': 'grocery.supermarket',

  // Online Grocery
  'MARKET KURLY': 'grocery.online_grocery',
  'KURLY INC': 'grocery.online_grocery',
  'SSG FRESH': 'grocery.online_grocery',
  'COUPANG ROCKET FRESH': 'grocery.online_grocery',
  'OASIS MARKET': 'grocery.online_grocery',
  'HELLO NATURE': 'grocery.online_grocery',

  // Convenience Store
  'CU CONVENIENCE': 'convenience_store',
  'BGF RETAIL': 'convenience_store',
  'GS25': 'convenience_store',
  'GS RETAIL': 'convenience_store',
  'SEVEN ELEVEN KOREA': 'convenience_store',
  '7 ELEVEN KOREA': 'convenience_store',
  'COREA ELEVEN': 'convenience_store',
  'EMART 24': 'convenience_store',
  'EMART24': 'convenience_store',
  'MINISTOP KOREA': 'convenience_store',
  'MINISTOP': 'convenience_store',

  // Department Store / Offline Shopping
  'LOTTE DEPT STORE': 'offline_shopping.department_store',
  'LOTTE DEPARTMENT': 'offline_shopping.department_store',
  'SHINSEGAE DEPT': 'offline_shopping.department_store',
  'SHINSEGAE DEPARTMENT': 'offline_shopping.department_store',
  'HYUNDAI DEPT STORE': 'offline_shopping.department_store',
  'HYUNDAI DEPARTMENT': 'offline_shopping.department_store',
  'GALLERIA DEPT': 'offline_shopping.department_store',
  'GALLERIA': 'offline_shopping.department_store',
  'AK PLAZA': 'offline_shopping.department_store',
  'NC DEPARTMENT': 'offline_shopping.department_store',
  'LOTTE OUTLETS': 'offline_shopping.department_store',
  'HYUNDAI PREMIUM OUTLETS': 'offline_shopping.department_store',
  'SHINSEGAE OUTLETS': 'offline_shopping.department_store',

  // Cosmetics / Health & Beauty
  'OLIVE YOUNG CO': 'offline_shopping',
  'CJ OLIVE YOUNG': 'offline_shopping',
  'CJ OLIVENETWORKS': 'offline_shopping',
  'OLIVE YOUNG': 'offline_shopping',
  'AMORE PACIFIC': 'offline_shopping',
  'AMOREPACIFIC': 'offline_shopping',
  'INNISFREE': 'offline_shopping',
  'ETUDE HOUSE': 'offline_shopping',
  'ETUDE': 'offline_shopping',
  'LANEIGE': 'offline_shopping',
  'SULWHASOO': 'offline_shopping',
  'IOPE': 'offline_shopping',
  'HERA COSMETICS': 'offline_shopping',
  'ESPOIR': 'offline_shopping',
  'LG HOUSEHOLD': 'offline_shopping',
  'LG H AND H': 'offline_shopping',
  'THE FACE SHOP': 'offline_shopping',
  'THEFACESHOP': 'offline_shopping',
  'NATURE REPUBLIC': 'offline_shopping',
  'SKINFOOD': 'offline_shopping',
  'SKIN FOOD': 'offline_shopping',
  'MISSHA': 'offline_shopping',
  'ABLE C AND C': 'offline_shopping',
  'TONY MOLY': 'offline_shopping',
  'TONYMOLY': 'offline_shopping',
  'ROMAND': 'offline_shopping',
  'CLIO': 'offline_shopping',
  'PERIPERA': 'offline_shopping',
  'BANILA CO': 'offline_shopping',
  'LRCRAFT': 'offline_shopping',
  'BEAUTY NET KOREA': 'offline_shopping',
  'LOBS HEALTH BEAUTY': 'offline_shopping',

  // Lifestyle / General Retail
  'DAISO KOREA': 'offline_shopping',
  'DAISO INDUSTRIES KR': 'offline_shopping',
  'DAISO': 'offline_shopping',
  'ARTBOX': 'offline_shopping',
  'DAISOMALL': 'offline_shopping',
  'NATUREHIKE': 'offline_shopping',
  'IKEYA KOREA': 'offline_shopping',
  'IKEA KOREA': 'offline_shopping',
  'IKEA': 'offline_shopping',
  'MUJI KOREA': 'offline_shopping',
  'MUJI': 'offline_shopping',
  'MINISO KOREA': 'offline_shopping',
  'MINISO': 'offline_shopping',

  // Cinema
  'CGV CO LTD': 'entertainment.movie',
  'CJ CGV': 'entertainment.movie',
  'CGV MULTIPLEX': 'entertainment.movie',
  'CGV': 'entertainment.movie',
  'MEGABOX CO LTD': 'entertainment.movie',
  'MEGABOX CINEMA': 'entertainment.movie',
  'MEGABOX': 'entertainment.movie',
  'LOTTE CINEMA CO': 'entertainment.movie',
  'LOTTE CULTUREWORKS': 'entertainment.movie',
  'LOTTE CINEMA': 'entertainment.movie',

  // Online Shopping
  'COUPANG CORP': 'online_shopping',
  'COUPANG INC': 'online_shopping',
  'COUPANG LLC': 'online_shopping',
  'COUPANG': 'online_shopping',
  'NAVER CORP': 'online_shopping',
  'NAVER PAY CORP': 'online_shopping',
  'NAVER FINANCIAL': 'online_shopping',
  'NAVER SHOPPING': 'online_shopping',
  'NAVER': 'online_shopping',
  'KAKAO CORP': 'online_shopping',
  'KAKAO PAY CORP': 'online_shopping',
  'KAKAO COMMERCE': 'online_shopping',
  'KAKAO SHOPPING': 'online_shopping',
  'SSG DOT COM': 'online_shopping',
  'SSG COM': 'online_shopping',
  'SSG': 'online_shopping',
  'GMARKET INC': 'online_shopping',
  'GMARKET': 'online_shopping',
  'AUCTION CO LTD': 'online_shopping',
  'AUCTION': 'online_shopping',
  'TMON CO LTD': 'online_shopping',
  'TMON': 'online_shopping',
  'WEMAKEPRICE': 'online_shopping',
  'INTERPARK COMMERCE': 'online_shopping',
  'INTERPARK': 'online_shopping',
  'LOTTE ON': 'online_shopping',
  'LOTTEON': 'online_shopping',
  '11ST': 'online_shopping',
  'SK PLANET': 'online_shopping',

  // Fashion
  'MUSINSA CO LTD': 'online_shopping.fashion',
  'MUSINSA': 'online_shopping.fashion',
  'ZIGZAG': 'online_shopping.fashion',
  'ABLY': 'online_shopping.fashion',
  'W CONCEPT': 'online_shopping.fashion',
  '29CM': 'online_shopping.fashion',
  'BRANDI': 'online_shopping.fashion',
  'HAGO': 'online_shopping.fashion',
  'UNIQLO KOREA': 'online_shopping.fashion',
  'FAST RETAILING KR': 'online_shopping.fashion',
  'FAST RETAILING': 'online_shopping.fashion',
  'UNIQLO': 'online_shopping.fashion',
  'ZARA KOREA': 'online_shopping.fashion',
  'INDITEX KOREA': 'online_shopping.fashion',
  'INDITEX': 'online_shopping.fashion',
  'ZARA': 'online_shopping.fashion',
  'H AND M KOREA': 'online_shopping.fashion',
  'H M KOREA': 'online_shopping.fashion',
  'H AND M': 'online_shopping.fashion',
  'H M': 'online_shopping.fashion',
  'NIKE KOREA': 'online_shopping.fashion',
  'NIKE': 'online_shopping.fashion',
  'ADIDAS KOREA': 'online_shopping.fashion',
  'ADIDAS': 'online_shopping.fashion',
  'NEW BALANCE KOREA': 'online_shopping.fashion',
  'NEW BALANCE': 'online_shopping.fashion',
  'PUMA KOREA': 'online_shopping.fashion',
  'PUMA': 'online_shopping.fashion',
  'REEBOK KOREA': 'online_shopping.fashion',
  'REEBOK': 'online_shopping.fashion',
  'UNDER ARMOUR': 'online_shopping.fashion',
  'UNDER ARMOUR KOREA': 'online_shopping.fashion',
  'GAP KOREA': 'online_shopping.fashion',
  'GAP': 'online_shopping.fashion',
  'POLO RALPH LAUREN': 'online_shopping.fashion',
  'RALPH LAUREN': 'online_shopping.fashion',
  'TOMMY HILFIGER': 'online_shopping.fashion',
  'TOMMY': 'online_shopping.fashion',
  'LEVI S KOREA': 'online_shopping.fashion',
  'LEVIS': 'online_shopping.fashion',
  'CALVIN KLEIN KOREA': 'online_shopping.fashion',
  'CALVIN KLEIN': 'online_shopping.fashion',
  'LACOSTE KOREA': 'online_shopping.fashion',
  'LACOSTE': 'online_shopping.fashion',
  'GUESS KOREA': 'online_shopping.fashion',
  'GUESS': 'online_shopping.fashion',
  'GUESS FACTORY': 'online_shopping.fashion',
  'TOPTEN': 'online_shopping.fashion',
  'SPAO': 'online_shopping.fashion',
  'MIXXO': 'online_shopping.fashion',
  'NERDY': 'online_shopping.fashion',
  'MLB KOREA': 'online_shopping.fashion',
  'F F KOREA': 'online_shopping.fashion',
  'DISCOVERY EXPEDITION': 'online_shopping.fashion',
  'THE NORTH FACE KOREA': 'online_shopping.fashion',
  'THE NORTH FACE': 'online_shopping.fashion',
  'COLUMBIA SPORTSWEAR KR': 'online_shopping.fashion',
  'COLUMBIA': 'online_shopping.fashion',
  'PATAGONIA KOREA': 'online_shopping.fashion',
  'PATAGONIA': 'online_shopping.fashion',
  'ARC TERYX KOREA': 'online_shopping.fashion',
  'ARCTERYX': 'online_shopping.fashion',
  'K2 KOREA': 'online_shopping.fashion',
  'BLACKYAK': 'online_shopping.fashion',
  'KOLON SPORT': 'online_shopping.fashion',
  'MAMMUT KOREA': 'online_shopping.fashion',
  'SALOMON KOREA': 'online_shopping.fashion',

  // Telecom
  'SK TELECOM': 'telecom',
  'SK TELECOM CO': 'telecom',
  'SK TELECOM LTD': 'telecom',
  'SK T': 'telecom',
  'KT CORP': 'telecom',
  'KT CO LTD': 'telecom',
  'LG UPLUS': 'telecom',
  'LG U PLUS': 'telecom',
  'LG TELECOM': 'telecom',
  'KT SKYLIFE': 'telecom',
  'KT OLLEH': 'telecom',
  'HELLOVISION': 'telecom',

  // Fuel / Gas Station
  'SK ENERGY': 'transportation.fuel',
  'SK ENXEN': 'transportation.fuel',
  'GS CALTEX': 'transportation.fuel',
  'GS CALTEX CORP': 'transportation.fuel',
  'S OIL CORP': 'transportation.fuel',
  'S OIL': 'transportation.fuel',
  'HYUNDAI OILBANK': 'transportation.fuel',
  'HYUNDAI OIL': 'transportation.fuel',
  'OILBANK': 'transportation.fuel',
  'SHELL KOREA': 'transportation.fuel',
  'SHELL': 'transportation.fuel',
  'SELF OIL': 'transportation.fuel',

  // Toll / Highway
  'HIPASS': 'transportation.toll',
  'HI PASS': 'transportation.toll',
  'KOREA EXPRESSWAY': 'transportation.toll',
  'KOREA EXPRESSWAY CORP': 'transportation.toll',
  'EX HIPASS': 'transportation.toll',

  // Taxi / Ride
  'KAKAO MOBILITY': 'public_transit.taxi',
  'KAKAO T': 'public_transit.taxi',
  'TADA': 'public_transit.taxi',
  'UBER KOREA': 'public_transit.taxi',
  'UBER': 'public_transit.taxi',
  'ONDA MOBILITY': 'public_transit.taxi',
  'CAREEM': 'public_transit.taxi',
  'TMONEY GO': 'public_transit.taxi',

  // Train / Rail
  'KORAIL': 'public_transit.subway',
  'KOREA RAILROAD': 'public_transit.subway',
  'SR CORP': 'public_transit.subway',
  'SRT': 'public_transit.subway',
  'SEOUL METRO': 'public_transit.subway',
  'BUSAN METRO': 'public_transit.subway',
  'DAEGU METRO': 'public_transit.subway',
  'INCHEON METRO': 'public_transit.subway',
  'GWANGJU METRO': 'public_transit.subway',
  'DAEJEON METRO': 'public_transit.subway',
  'SHINBUNDANG LINE': 'public_transit.subway',

  // Airline (Korean)
  'KOREAN AIR': 'travel.airline',
  'KOREAN AIR LINES': 'travel.airline',
  'KE AIRLINES': 'travel.airline',
  'ASIANA AIRLINES': 'travel.airline',
  'ASIANA': 'travel.airline',
  'JEJU AIR': 'travel.airline',
  'JIN AIR': 'travel.airline',
  'T WAY AIR': 'travel.airline',
  'TWAY AIR': 'travel.airline',
  'AIR BUSAN': 'travel.airline',
  'AIR SEOUL': 'travel.airline',
  'AERO K': 'travel.airline',
  'FLY GANGWON': 'travel.airline',
  'AIR INCHEON': 'travel.airline',

  // Hotel (Korean)
  'LOTTE HOTEL': 'travel.hotel',
  'LOTTE RESORT': 'travel.hotel',
  'SHILLA HOTEL': 'travel.hotel',
  'THE SHILLA': 'travel.hotel',
  'GRAND HYATT KOREA': 'travel.hotel',
  'HYATT REGENCY KOREA': 'travel.hotel',
  'SIGNIEL': 'travel.hotel',
  'HOTEL LOTTE': 'travel.hotel',
  'PARADISE HOTEL': 'travel.hotel',
  'WALKERHILL': 'travel.hotel',
  'GRAND WALKERHILL': 'travel.hotel',
  'BANYAN TREE CLUB': 'travel.hotel',
  'JOSUN HOTEL': 'travel.hotel',

  // Travel Agency (Korean)
  'HANATOUR': 'travel.travel_agency',
  'MODETOUR': 'travel.travel_agency',
  'YELLOW BALLOON': 'travel.travel_agency',
  'INTERPARK TOURS': 'travel.travel_agency',
  'YANOLJA': 'travel.hotel',
  'YANOLJA CO': 'travel.hotel',
  'YEOGI EOTTAE': 'travel.hotel',

  // Streaming / Entertainment (Korean)
  'NETFLIX KOREA': 'entertainment.streaming',
  'WAVVE': 'entertainment.streaming',
  'TVING': 'entertainment.streaming',
  'COUPANG PLAY': 'entertainment.streaming',
  'WATCHA': 'entertainment.streaming',
  'MELON MUSIC': 'entertainment.streaming',
  'GENIE MUSIC': 'entertainment.streaming',
  'FLOOP': 'entertainment.streaming',
  'NAVERWEBTOON': 'entertainment',
  'NAVER WEBTOON': 'entertainment',
  'KAKAO PAGE': 'entertainment',
  'KAKAOTALK': 'online_shopping',

  // Books / Education
  'KYOBO BOOKSTORE': 'education.books',
  'KYOBO': 'education.books',
  'YOUNGPOONG BOOKSTORE': 'education.books',
  'ALADDIN': 'education.books',
  'YES24': 'education.books',
  'BANDI LUNIS': 'education.books',

  // Insurance
  'SAMSUNG LIFE': 'insurance',
  'SAMSUNG FIRE': 'insurance',
  'HANWHA LIFE': 'insurance',
  'KYOBO LIFE': 'insurance',
  'HYUNDAI MARINE': 'insurance',
  'DB INSURANCE': 'insurance',
  'KB INSURANCE': 'insurance',
  'MERITZ FIRE': 'insurance',
  'LOTTE INSURANCE': 'insurance',
  'HEUNGKUK LIFE': 'insurance',

  // Utilities
  'KEPCO': 'utilities.electricity',
  'KOREA ELECTRIC POWER': 'utilities.electricity',
  'KOGAS': 'utilities.gas',
  'KOREA GAS': 'utilities.gas',

  // ── Section 2: Global brands UPPERCASE ──

  // Amazon
  'AMAZON COM': 'online_shopping',
  'AMAZON PAYMENTS': 'online_shopping',
  'AMAZON PRIME': 'subscription',
  'AMAZON PRIME VIDEO': 'entertainment.streaming',
  'AMAZON KINDLE': 'entertainment.streaming',
  'AMAZON MUSIC': 'entertainment.streaming',
  'AMAZON MUSIC UNLIMITED': 'entertainment.streaming',
  'AMAZON WEB SERVICES': 'subscription',
  'AWS': 'subscription',
  'AMAZON AUDIBLE': 'entertainment.streaming',
  'AUDIBLE': 'entertainment.streaming',
  'AMAZON GAMING': 'entertainment',
  'AMAZON FRESH': 'grocery.online_grocery',

  // Netflix
  'NETFLIX COM': 'entertainment.streaming',
  'NETFLIX INC': 'entertainment.streaming',
  'NETFLIX MONTHLY': 'entertainment.streaming',
  'NETFLIX': 'entertainment.streaming',

  // Spotify
  'SPOTIFY AB': 'entertainment.streaming',
  'SPOTIFY USA': 'entertainment.streaming',
  'SPOTIFY': 'entertainment.streaming',

  // Apple
  'APPLE COM BILL': 'entertainment',
  'APPLE ITUNES': 'entertainment',
  'APPLE MUSIC': 'entertainment.streaming',
  'APPLE TV PLUS': 'entertainment.streaming',
  'APPLE TV': 'entertainment.streaming',
  'APPLE ICLOUD': 'subscription',
  'APPLE ONE': 'subscription',
  'APPLE ARCADE': 'entertainment',
  'APPLE NEWS': 'subscription',
  'APPLE FITNESS': 'subscription',
  'APPLE STORE': 'online_shopping',
  'ITUNES': 'entertainment',
  'APP STORE': 'entertainment',

  // Google
  'GOOGLE PLAY': 'entertainment',
  'GOOGLE ONE': 'subscription',
  'GOOGLE STORAGE': 'subscription',
  'GOOGLE WORKSPACE': 'subscription',
  'GOOGLE CLOUD': 'subscription',
  'GOOGLE ADS': 'subscription',
  'GOOGLE LLC': 'subscription',
  'GOOGLE YOUTUBE': 'entertainment.streaming',
  'YOUTUBE PREMIUM': 'entertainment.streaming',
  'YOUTUBE MUSIC': 'entertainment.streaming',
  'YOUTUBE': 'entertainment.streaming',
  'GOOGLE STADIA': 'entertainment',

  // Microsoft
  'MICROSOFT 365': 'subscription',
  'MICROSOFT OFFICE': 'subscription',
  'MICROSOFT AZURE': 'subscription',
  'MICROSOFT CORP': 'subscription',
  'MICROSOFT': 'subscription',
  'XBOX GAME PASS': 'entertainment',
  'XBOX LIVE': 'entertainment',
  'XBOX': 'entertainment',
  'WINDOWS': 'subscription',

  // Adobe
  'ADOBE INC': 'subscription',
  'ADOBE CREATIVE CLOUD': 'subscription',
  'ADOBE ACROBAT': 'subscription',
  'ADOBE STOCK': 'subscription',
  'ADOBE': 'subscription',

  // Zoom / Video
  'ZOOM VIDEO COMM': 'subscription',
  'ZOOM US': 'subscription',
  'ZOOM': 'subscription',

  // AI / LLM
  'OPENAI LLC': 'subscription',
  'OPENAI': 'subscription',
  'CHATGPT PLUS': 'subscription',
  'CHATGPT PRO': 'subscription',
  'CHATGPT': 'subscription',
  'CLAUDE AI': 'subscription',
  'ANTHROPIC': 'subscription',
  'ANTHROPIC PBC': 'subscription',
  'MIDJOURNEY': 'subscription',
  'GITHUB COPILOT': 'subscription',
  'PERPLEXITY AI': 'subscription',
  'PERPLEXITY': 'subscription',
  'JASPER AI': 'subscription',
  'COPY AI': 'subscription',

  // Dev Tools / SaaS
  'GITHUB INC': 'subscription',
  'GITHUB': 'subscription',
  'NOTION LABS': 'subscription',
  'NOTION': 'subscription',
  'FIGMA INC': 'subscription',
  'FIGMA': 'subscription',
  'CANVA PTY': 'subscription',
  'CANVA': 'subscription',
  'SLACK TECH': 'subscription',
  'SLACK': 'subscription',
  'ATLASSIAN': 'subscription',
  'ATLASSIAN PTY': 'subscription',
  'JIRA': 'subscription',
  'CONFLUENCE': 'subscription',
  'TRELLO': 'subscription',
  'DROPBOX INC': 'subscription',
  'DROPBOX': 'subscription',
  'EVERNOTE': 'subscription',
  'GRAMMARLY': 'subscription',
  'GRAMMARLY INC': 'subscription',
  'LOOM': 'subscription',
  'ZAPIER': 'subscription',
  'AIRTABLE': 'subscription',
  'MIRO': 'subscription',
  'LINEAR': 'subscription',
  'VERCEL': 'subscription',
  'NETLIFY': 'subscription',
  'HEROKU': 'subscription',
  'DIGITALOCEAN': 'subscription',
  'LINODE': 'subscription',
  'CLOUDFLARE': 'subscription',
  'STRIPE': 'subscription',
  'TWILIO': 'subscription',
  'SENDGRID': 'subscription',
  'MAILCHIMP': 'subscription',
  'HUBSPOT': 'subscription',
  'SALESFORCE': 'subscription',
  'SERVICENOW': 'subscription',
  'WORKDAY': 'subscription',
  'DOCUSIGN': 'subscription',
  '1PASSWORD': 'subscription',
  'LASTPASS': 'subscription',
  'BITWARDEN': 'subscription',
  'NORDVPN': 'subscription',
  'EXPRESSVPN': 'subscription',
  'NORD VPN': 'subscription',
  'PROTONMAIL': 'subscription',
  'FASTMAIL': 'subscription',
  'PCLOUD': 'subscription',
  'BOX INC': 'subscription',

  // Gaming
  'STEAM': 'entertainment',
  'VALVE CORP': 'entertainment',
  'STEAM GAMES': 'entertainment',
  'NINTENDO ESHOP': 'entertainment',
  'NINTENDO': 'entertainment',
  'PLAYSTATION STORE': 'entertainment',
  'PLAYSTATION': 'entertainment',
  'SONY INTERACTIVE': 'entertainment',
  'EA GAMES': 'entertainment',
  'ELECTRONIC ARTS': 'entertainment',
  'BLIZZARD': 'entertainment',
  'ACTIVISION': 'entertainment',
  'UBISOFT': 'entertainment',
  'EPIC GAMES': 'entertainment',
  'RIOT GAMES': 'entertainment',
  'NEXON': 'entertainment',
  'NETMARBLE': 'entertainment',
  'NCSOFT': 'entertainment',
  'KRAFTON': 'entertainment',
  'KAKAO GAMES': 'entertainment',
  'SMILEGATE': 'entertainment',
  'WEMADE': 'entertainment',

  // Streaming / Media (global)
  'DISNEY PLUS': 'entertainment.streaming',
  'DISNEY BUNDLE': 'entertainment.streaming',
  'DISNEY': 'entertainment.streaming',
  'HULU': 'entertainment.streaming',
  'HBO MAX': 'entertainment.streaming',
  'MAX': 'entertainment.streaming',
  'PARAMOUNT PLUS': 'entertainment.streaming',
  'PEACOCK': 'entertainment.streaming',
  'DISCOVERY PLUS': 'entertainment.streaming',
  'CRUNCHYROLL': 'entertainment.streaming',
  'FUNIMATION': 'entertainment.streaming',
  'TWITCH': 'entertainment.streaming',
  'DAZN': 'entertainment.streaming',
  'ESPN PLUS': 'entertainment.streaming',
  'APPLE TV CHANNEL': 'entertainment.streaming',

  // Global Retail / e-Commerce
  'EBAY': 'online_shopping',
  'EBAY INC': 'online_shopping',
  'ALIEXPRESS': 'online_shopping',
  'ALIBABA': 'online_shopping',
  'SHEIN': 'online_shopping.fashion',
  'SHEIN COM': 'online_shopping.fashion',
  'WISH': 'online_shopping',
  'RAKUTEN': 'online_shopping',
  'MERCARI': 'online_shopping',
  'ETSY': 'online_shopping',
  'ETSY INC': 'online_shopping',
  'SHOPIFY': 'online_shopping',
  'WALMART': 'grocery.supermarket',
  'TARGET': 'offline_shopping',
  'BEST BUY': 'offline_shopping',
  'BESTBUY': 'offline_shopping',
  'NORDSTROM': 'online_shopping.fashion',
  'MACY S': 'offline_shopping',
  'BLOOMINGDALES': 'offline_shopping',
  'SAKS FIFTH AVE': 'offline_shopping',
  'NEIMAN MARCUS': 'offline_shopping',

  // Luxury
  'LOUIS VUITTON': 'online_shopping.fashion',
  'CHANEL': 'online_shopping.fashion',
  'GUCCI': 'online_shopping.fashion',
  'PRADA': 'online_shopping.fashion',
  'HERMES': 'online_shopping.fashion',
  'BURBERRY': 'online_shopping.fashion',
  'VERSACE': 'online_shopping.fashion',
  'FENDI': 'online_shopping.fashion',
  'BALENCIAGA': 'online_shopping.fashion',
  'GIVENCHY': 'online_shopping.fashion',
  'BOTTEGA VENETA': 'online_shopping.fashion',
  'SAINT LAURENT': 'online_shopping.fashion',
  'DIOR': 'online_shopping.fashion',
  'VALENTINO': 'online_shopping.fashion',
  'CELINE': 'online_shopping.fashion',
  'LOEWE': 'online_shopping.fashion',
  'MONCLER': 'online_shopping.fashion',
  'CANADA GOOSE': 'online_shopping.fashion',
  'STONE ISLAND': 'online_shopping.fashion',
  'TORY BURCH': 'online_shopping.fashion',
  'MICHAEL KORS': 'online_shopping.fashion',
  'COACH': 'online_shopping.fashion',
  'KATE SPADE': 'online_shopping.fashion',
  'MARC JACOBS': 'online_shopping.fashion',

  // Global Fast Fashion
  'FOREVER 21': 'online_shopping.fashion',
  'PRIMARK': 'online_shopping.fashion',
  'MANGO': 'online_shopping.fashion',
  'TOPSHOP': 'online_shopping.fashion',
  'ASOS': 'online_shopping.fashion',
  'BOOHOO': 'online_shopping.fashion',
  'PRETTY LITTLE THING': 'online_shopping.fashion',
  'SHEIN FASHION': 'online_shopping.fashion',

  // Global Airlines
  'DELTA AIR LINES': 'travel.airline',
  'DELTA AIRLINES': 'travel.airline',
  'AMERICAN AIRLINES': 'travel.airline',
  'UNITED AIRLINES': 'travel.airline',
  'SOUTHWEST AIRLINES': 'travel.airline',
  'ALASKA AIRLINES': 'travel.airline',
  'JETBLUE AIRWAYS': 'travel.airline',
  'SPIRIT AIRLINES': 'travel.airline',
  'FRONTIER AIRLINES': 'travel.airline',
  'BRITISH AIRWAYS': 'travel.airline',
  'LUFTHANSA': 'travel.airline',
  'AIR FRANCE': 'travel.airline',
  'KLM': 'travel.airline',
  'EMIRATES': 'travel.airline',
  'ETIHAD AIRWAYS': 'travel.airline',
  'QATAR AIRWAYS': 'travel.airline',
  'SINGAPORE AIRLINES': 'travel.airline',
  'CATHAY PACIFIC': 'travel.airline',
  'JAPAN AIRLINES': 'travel.airline',
  'ALL NIPPON AIRWAYS': 'travel.airline',
  'ANA': 'travel.airline',
  'JAL': 'travel.airline',
  'EVA AIR': 'travel.airline',
  'CHINA SOUTHERN': 'travel.airline',
  'CHINA EASTERN': 'travel.airline',
  'AIR CHINA': 'travel.airline',
  'THAI AIRWAYS': 'travel.airline',
  'VIETNAM AIRLINES': 'travel.airline',
  'AIR ASIA': 'travel.airline',
  'AIRASIA': 'travel.airline',
  'SCOOT': 'travel.airline',
  'JETSTAR': 'travel.airline',
  'QANTAS': 'travel.airline',
  'AIR NEW ZEALAND': 'travel.airline',
  'TURKISH AIRLINES': 'travel.airline',
  'FINNAIR': 'travel.airline',
  'SWISS AIR': 'travel.airline',
  'AUSTRIAN AIRLINES': 'travel.airline',
  'IBERIA': 'travel.airline',
  'RYANAIR': 'travel.airline',
  'EASYJET': 'travel.airline',
  'WIZZ AIR': 'travel.airline',
  'CEBU PACIFIC': 'travel.airline',
  'PHILIPPINE AIRLINES': 'travel.airline',
  'GARUDA INDONESIA': 'travel.airline',
  'LION AIR': 'travel.airline',
  'BATIK AIR': 'travel.airline',
  'INDIGO': 'travel.airline',
  'AIR INDIA': 'travel.airline',
  'SPICEJET': 'travel.airline',
  'GO FIRST': 'travel.airline',
  'TIGERAIR': 'travel.airline',
  'ROYAL BRUNEI': 'travel.airline',
  'ROYAL JORDANIAN': 'travel.airline',
  'MALAYSIA AIRLINES': 'travel.airline',
  'TAROM': 'travel.airline',

  // Global Hotels / OTA
  'MARRIOTT': 'travel.hotel',
  'MARRIOTT BONVOY': 'travel.hotel',
  'HILTON HOTELS': 'travel.hotel',
  'HILTON': 'travel.hotel',
  'HYATT': 'travel.hotel',
  'SHERATON': 'travel.hotel',
  'WESTIN': 'travel.hotel',
  'W HOTELS': 'travel.hotel',
  'INTERCONTINENTAL': 'travel.hotel',
  'HOLIDAY INN': 'travel.hotel',
  'CROWNE PLAZA': 'travel.hotel',
  'BEST WESTERN': 'travel.hotel',
  'RADISSON': 'travel.hotel',
  'WYNDHAM': 'travel.hotel',
  'FOUR SEASONS': 'travel.hotel',
  'RITZ CARLTON': 'travel.hotel',
  'ST REGIS': 'travel.hotel',
  'FAIRMONT': 'travel.hotel',
  'NOVOTEL': 'travel.hotel',
  'IBIS': 'travel.hotel',
  'SOFITEL': 'travel.hotel',
  'ACCOR HOTELS': 'travel.hotel',
  'ACCOR': 'travel.hotel',
  'MANDARIN ORIENTAL': 'travel.hotel',
  'PENINSULA HOTELS': 'travel.hotel',
  'AIRBNB': 'travel.hotel',
  'AIRBNB INC': 'travel.hotel',
  'HOTELS COM': 'travel.hotel',
  'BOOKING COM': 'travel.hotel',
  'EXPEDIA': 'travel.travel_agency',
  'AGODA': 'travel.hotel',
  'KAYAK': 'travel.travel_agency',
  'TRIVAGO': 'travel.hotel',
  'TRIP COM': 'travel.travel_agency',
  'CTRIP': 'travel.travel_agency',
  'KLOOK': 'travel.travel_agency',
  'VIATOR': 'travel.travel_agency',
  'TRIPADVISOR': 'travel.travel_agency',
  'HOSTELWORLD': 'travel.hotel',
  'VRBO': 'travel.hotel',

  // Car Rental / Ride Share
  'HERTZ': 'transportation',
  'AVIS': 'transportation',
  'ENTERPRISE RENT': 'transportation',
  'BUDGET RENT': 'transportation',
  'SIXT': 'transportation',
  'EUROPCAR': 'transportation',
  'ALAMO': 'transportation',
  'NATIONAL CAR': 'transportation',
  'GRAB': 'public_transit.taxi',
  'GRAB TAXI': 'public_transit.taxi',
  'GOJEK': 'public_transit.taxi',
  'OLA CABS': 'public_transit.taxi',
  'OLA': 'public_transit.taxi',
  'LYFT': 'public_transit.taxi',
  'BOLT RIDE': 'public_transit.taxi',
  'DIDI': 'public_transit.taxi',
  'DIDI CHUXING': 'public_transit.taxi',
  'RAPIDO': 'public_transit.taxi',

  // Global Food Delivery
  'DOORDASH': 'dining.delivery',
  'DOORDASH INC': 'dining.delivery',
  'UBER EATS': 'dining.delivery',
  'GRUBHUB': 'dining.delivery',
  'INSTACART': 'grocery.online_grocery',
  'DELIVEROO': 'dining.delivery',
  'JUST EAT': 'dining.delivery',
  'FOODPANDA': 'dining.delivery',
  'SWIGGY': 'dining.delivery',
  'ZOMATO': 'dining.delivery',
  'TALABAT': 'dining.delivery',
  'MRSPEEDY': 'dining.delivery',

  // Global Coffee / Food Chains
  'MCDONALDS US': 'dining.fast_food',
  'WENDYS US': 'dining.fast_food',
  'CHIPOTLE': 'dining.fast_food',
  'PANERA BREAD': 'dining.cafe',
  'PRET A MANGER': 'dining.cafe',
  'COSTA COFFEE': 'dining.cafe',
  'TIM HORTONS': 'dining.cafe',
  'CARIBOU COFFEE': 'dining.cafe',
  'PEETS COFFEE': 'dining.cafe',
  'COFFEE HOUSE': 'dining.cafe',
  'COFFEE FELLOWS': 'dining.cafe',
  'SECOND CUP': 'dining.cafe',
  'NESPRESSO': 'dining.cafe',
  'TACO BELL US': 'dining.fast_food',
  'JACK IN THE BOX': 'dining.fast_food',
  'SONIC DRIVE IN': 'dining.fast_food',
  'DAIRY QUEEN': 'dining.cafe',
  'COLD STONE': 'dining.cafe',
  'BEN AND JERRYS': 'dining.cafe',
  'CARVEL': 'dining.cafe',
  'WINGSTOP': 'dining.fast_food',
  'NANDOS': 'dining.restaurant',
  'WAGAMAMA': 'dining.restaurant',
  'YO SUSHI': 'dining.restaurant',
  'POKE BROS': 'dining.restaurant',
  'SWEETGREEN': 'dining.restaurant',
  'FRESHII': 'dining.restaurant',

  // Global Supermarkets
  'WHOLE FOODS MARKET': 'grocery.supermarket',
  'WHOLE FOODS': 'grocery.supermarket',
  'TRADER JOES': 'grocery.supermarket',
  'KROGER': 'grocery.supermarket',
  'PUBLIX': 'grocery.supermarket',
  'SAFEWAY': 'grocery.supermarket',
  'ALBERTSONS': 'grocery.supermarket',
  'CARREFOUR': 'grocery.supermarket',
  'TESCO': 'grocery.supermarket',
  'SAINSBURYS': 'grocery.supermarket',
  'ASDA': 'grocery.supermarket',
  'LIDL': 'grocery.supermarket',
  'ALDI': 'grocery.supermarket',
  'REWE': 'grocery.supermarket',
  'EDEKA': 'grocery.supermarket',
  'PENNY MARKET': 'grocery.supermarket',
  'SPAR': 'grocery.supermarket',
  'METRO CASH': 'grocery.supermarket',
  'COLES SUPERMARKETS': 'grocery.supermarket',
  'WOOLWORTHS AU': 'grocery.supermarket',
  'IGA': 'grocery.supermarket',
  'COUNTDOWN': 'grocery.supermarket',
  'FAIRPRICE': 'grocery.supermarket',
  'COLD STORAGE': 'grocery.supermarket',
  'GIANT HYPERMART': 'grocery.supermarket',
  'AEON MALL': 'grocery.supermarket',
  'ION ORCHARD': 'offline_shopping',

  // Global Pharmacy
  'CVS PHARMACY': 'medical.pharmacy',
  'CVS': 'medical.pharmacy',
  'WALGREENS': 'medical.pharmacy',
  'RITE AID': 'medical.pharmacy',
  'BOOTS': 'medical.pharmacy',
  'SUPERDRUG': 'medical.pharmacy',
  'WATSON S': 'medical.pharmacy',
  'WATSONS': 'medical.pharmacy',
  'GUARDIAN PHARMACY': 'medical.pharmacy',
  'MERCURY DRUG': 'medical.pharmacy',

  // Global Electronics
  'APPLE STORE US': 'online_shopping',
  'BEST BUY US': 'offline_shopping',
  'CURRYS': 'offline_shopping',
  'MEDIA MARKT': 'offline_shopping',
  'SATURN': 'offline_shopping',
  'FNAC': 'offline_shopping',
  'BOULANGER': 'offline_shopping',
  'SAMSUNG STORE': 'offline_shopping',
  'SAMSUNG': 'offline_shopping',
  'SONY STORE': 'offline_shopping',
  'MICROSOFT STORE': 'offline_shopping',
  'B AND H PHOTO': 'offline_shopping',
  'ADORAMA': 'offline_shopping',

  // ── Section 3: Australia / NZ / India / Middle East / LatAm ──

  // Australia
  'WOOLWORTHS': 'grocery.supermarket',
  'COLES': 'grocery.supermarket',
  'BIG W': 'offline_shopping',
  'KMART AUSTRALIA': 'offline_shopping',
  'TARGET AUSTRALIA': 'offline_shopping',
  'JB HI FI': 'offline_shopping',
  'HARVEY NORMAN': 'offline_shopping',
  'BUNNINGS': 'offline_shopping',
  'OFFICEWORKS': 'offline_shopping',
  'MYERS': 'offline_shopping',
  'MYER': 'offline_shopping',
  'DAVID JONES': 'offline_shopping',
  'REBEL SPORT': 'offline_shopping.department_store',
  'SUPER RETAIL': 'offline_shopping',
  'CHEMIST WAREHOUSE': 'medical.pharmacy',
  'PRICELINE PHARMACY': 'medical.pharmacy',
  'DAN MURPHYS': 'offline_shopping',
  'BWS': 'offline_shopping',
  'LIQUORLAND': 'offline_shopping',
  'NANDOS AU': 'dining.restaurant',
  'HUNGRY JACKS': 'dining.fast_food',
  'RED ROOSTER': 'dining.fast_food',
  'OPORTO': 'dining.fast_food',
  'GUZMAN Y GOMEZ': 'dining.fast_food',
  'ZAMBRERO': 'dining.restaurant',
  'THE COFFEE CLUB': 'dining.cafe',
  'GLORIA JEANS AU': 'dining.cafe',
  'BOOST JUICE': 'dining.cafe',
  'CHATIME': 'dining.cafe',
  'GONG CHA AU': 'dining.cafe',
  'SUBWAY AU': 'dining.fast_food',
  'DOMINOS AU': 'dining.delivery',
  'PIZZA HUT AU': 'dining.delivery',
  'UBER EATS AU': 'dining.delivery',
  'MENULOG': 'dining.delivery',
  'DOORDASH AU': 'dining.delivery',
  'CATCH COM AU': 'online_shopping',
  'KOGAN': 'online_shopping',
  'AMAZON AU': 'online_shopping',
  'EBAY AU': 'online_shopping',
  'AFTERPAY': 'online_shopping',
  'ZIP CO': 'online_shopping',
  'QANTAS AIRWAYS': 'travel.airline',
  'VIRGIN AUSTRALIA': 'travel.airline',
  'TIGERAIR AU': 'travel.airline',
  'BONZA': 'travel.airline',
  'REX AIRLINES': 'travel.airline',
  'SYDNEY TRAINS': 'public_transit.subway',
  'MELBOURNE METRO': 'public_transit.subway',
  'TRANSPERTH': 'public_transit.subway',
  'TRANSLINK QLD': 'public_transit.subway',
  'ADELAIDEMETRO': 'public_transit.subway',
  'MYKI': 'public_transit.subway',
  'OPAL CARD': 'public_transit.subway',

  // New Zealand
  'COUNTDOWN NZ': 'grocery.supermarket',
  'NEW WORLD NZ': 'grocery.supermarket',
  'PAKNSAVE': 'grocery.supermarket',
  'FOUR SQUARE NZ': 'grocery.supermarket',
  'MITRE 10': 'offline_shopping',
  'BUNNINGS NZ': 'offline_shopping',
  'THE WAREHOUSE NZ': 'offline_shopping',
  'NOEL LEEMING': 'offline_shopping',
  'JB HIFI NZ': 'offline_shopping',
  'FARMERS NZ': 'offline_shopping',
  'AIR NEW ZEALAND NZ': 'travel.airline',
  'JETSTAR NZ': 'travel.airline',
  'NZ BUS': 'public_transit.bus',
  'MATES RATES': 'online_shopping',

  // India
  'FLIPKART': 'online_shopping',
  'FLIPKART INTERNET': 'online_shopping',
  'AMAZON INDIA': 'online_shopping',
  'MYNTRA': 'online_shopping.fashion',
  'MEESHO': 'online_shopping',
  'NYKAA': 'offline_shopping',
  'SNAPDEAL': 'online_shopping',
  'PAYTM MALL': 'online_shopping',
  'BIGBASKET': 'grocery.online_grocery',
  'GROFERS': 'grocery.online_grocery',
  'BLINKIT': 'grocery.online_grocery',
  'ZEPTO': 'grocery.online_grocery',
  'JIOMART': 'grocery.online_grocery',
  'RELIANCE FRESH': 'grocery.supermarket',
  'DMART': 'grocery.supermarket',
  'MORE RETAIL': 'grocery.supermarket',
  'SPENCER S': 'grocery.supermarket',
  'BIG BAZAAR': 'grocery.supermarket',
  'EASYDAY': 'grocery.supermarket',
  'ZOMATO INDIA': 'dining.delivery',
  'SWIGGY INDIA': 'dining.delivery',
  'DOMINOS INDIA': 'dining.delivery',
  'PIZZA HUT INDIA': 'dining.delivery',
  'MCDONALD S INDIA': 'dining.fast_food',
  'BURGER KING INDIA': 'dining.fast_food',
  'KFC INDIA': 'dining.fast_food',
  'CAFE COFFEE DAY': 'dining.cafe',
  'BARISTA COFFEE': 'dining.cafe',
  'CHAI POINT': 'dining.cafe',
  'CHAAYOS': 'dining.cafe',
  'STARBUCKS INDIA': 'dining.cafe',
  'INDIGO AIRLINES': 'travel.airline',
  'AIR INDIA IND': 'travel.airline',
  'SPICEJET INDIA': 'travel.airline',
  'AKASA AIR': 'travel.airline',
  'VISTARA': 'travel.airline',
  'OLA INDIA': 'public_transit.taxi',
  'RAPIDO BIKE': 'public_transit.taxi',
  'BOUNCE BIKES': 'public_transit.taxi',
  'UBER INDIA': 'public_transit.taxi',
  'PAYTM': 'online_shopping',
  'PHONEPE': 'online_shopping',
  'GPAY INDIA': 'online_shopping',
  'RELIANCE JIO': 'telecom',
  'AIRTEL INDIA': 'telecom',
  'BSNL': 'telecom',
  'VODAFONE INDIA': 'telecom',
  'MAKEMYTRIP': 'travel.travel_agency',
  'GOIBIBO': 'travel.travel_agency',
  'IXIGO': 'travel.travel_agency',
  'REDBUS': 'public_transit.bus',
  'IRCTC': 'public_transit.subway',

  // Middle East
  'CARREFOUR UAE': 'grocery.supermarket',
  'LULU HYPERMARKET': 'grocery.supermarket',
  'SPINNEYS': 'grocery.supermarket',
  'WAITROSE UAE': 'grocery.supermarket',
  'GEANT': 'grocery.supermarket',
  'UNION COOP': 'grocery.supermarket',
  'VIVA SUPERMARKET': 'grocery.supermarket',
  'PANDA SUPERSTORE': 'grocery.supermarket',
  'DANUBE SUPERMARKET': 'grocery.supermarket',
  'AMAZON UAE': 'online_shopping',
  'NOON COM': 'online_shopping',
  'NAMSHI': 'online_shopping.fashion',
  'OUNASS': 'online_shopping.fashion',
  'TALABAT UAE': 'dining.delivery',
  'DELIVEROO UAE': 'dining.delivery',
  'ZOMATO UAE': 'dining.delivery',
  'SHAWARMA GUYS': 'dining.restaurant',
  'EMIRATES AIRLINES': 'travel.airline',
  'FLYDUBAI': 'travel.airline',
  'AIR ARABIA': 'travel.airline',
  'FLYNAS': 'travel.airline',
  'SAUDIA': 'travel.airline',
  'GULF AIR': 'travel.airline',
  'OMAN AIR': 'travel.airline',
  'KUWAIT AIRWAYS': 'travel.airline',
  'CAREEM UAE': 'public_transit.taxi',
  'BOLT UAE': 'public_transit.taxi',
  'UBER UAE': 'public_transit.taxi',
  'DU TELECOM': 'telecom',
  'ETISALAT': 'telecom',
  'STC TELECOM': 'telecom',
  'ZAIN TELECOM': 'telecom',
  'MOBILY': 'telecom',
  'JAWWAL': 'telecom',
  'BOOKING UAE': 'travel.hotel',
  'JUMEIRAH GROUP': 'travel.hotel',
  'ROTANA HOTELS': 'travel.hotel',
  'DUBAI MALL': 'offline_shopping',
  'MALL OF EMIRATES': 'offline_shopping',
  'VIRGIN MEGASTORE': 'offline_shopping',
  'SOUQ COM': 'online_shopping',

  // Latin America
  'MERCADO LIBRE': 'online_shopping',
  'MERCADOLIBRE': 'online_shopping',
  'MERCADO PAGO': 'online_shopping',
  'RAPPI': 'dining.delivery',
  'IFOOD': 'dining.delivery',
  'PEDIDOS YA': 'dining.delivery',
  'CORNERSHOP': 'grocery.online_grocery',
  'UBER EATS LATAM': 'dining.delivery',
  'FALABELLA': 'offline_shopping',
  'RIPLEY': 'offline_shopping',
  'LIVERPOOL MX': 'offline_shopping',
  'COPPEL': 'offline_shopping',
  'WALMART MX': 'grocery.supermarket',
  'SORIANA': 'grocery.supermarket',
  'OXXO': 'convenience_store',
  'EXTRA': 'offline_shopping',
  'AMERICANAS': 'online_shopping',
  'SUBMARINO': 'online_shopping',
  'VIA VAREJO': 'online_shopping',
  'B2W DIGITAL': 'online_shopping',
  'AMAZON BRAZIL': 'online_shopping',
  'LATAM AIRLINES': 'travel.airline',
  'GOL AIRLINES': 'travel.airline',
  'AZUL AIRLINES': 'travel.airline',
  'AEROMEXICO': 'travel.airline',
  'VIVA AEROBUS': 'travel.airline',
  'INTERJET': 'travel.airline',
  'COPA AIRLINES': 'travel.airline',
  'AVIANCA': 'travel.airline',
  'SKY AIRLINE': 'travel.airline',
  'VOLARIS': 'travel.airline',
  'WINGO': 'travel.airline',
  'FLYBONDI': 'travel.airline',
  'EASY LATAM': 'travel.airline',
  '99 TAXIS': 'public_transit.taxi',
  'CABIFY': 'public_transit.taxi',
  'BEAT TAXI': 'public_transit.taxi',
  'CLARO TELECOM': 'telecom',
  'MOVISTAR': 'telecom',
  'TIM BRASIL': 'telecom',
  'OI TELECOM': 'telecom',
  'ENTEL': 'telecom',
  'TELCEL': 'telecom',

  // ── Section 4: Japan / China native script + Romanized ──

  // Japan - Coffee / Cafe
  'DOUTOR COFFEE': 'dining.cafe',
  'KOMEDA COFFEE': 'dining.cafe',
  'KOMEDA': 'dining.cafe',
  'TULLY S COFFEE': 'dining.cafe',
  'TULLYS': 'dining.cafe',
  'EXCELSIOR CAFFE': 'dining.cafe',
  'PRONTO CORP': 'dining.cafe',
  'CAFFE VELOCE': 'dining.cafe',
  'UESHIMA COFFEE': 'dining.cafe',
  'SAINT MARC CAFE': 'dining.cafe',
  'NONNON CAFE': 'dining.cafe',
  'OBI': 'offline_shopping',
  'ドトールコーヒー': 'dining.cafe',
  'コメダ珈琲店': 'dining.cafe',
  'タリーズコーヒー': 'dining.cafe',
  'エクセルシオール カフェ': 'dining.cafe',
  'プロント': 'dining.cafe',
  'カフェ・ベローチェ': 'dining.cafe',
  'スターバックスコーヒー': 'dining.cafe',
  'スターバックス': 'dining.cafe',
  'マクドナルド': 'dining.fast_food',
  'バーガーキング': 'dining.fast_food',
  'モスバーガー': 'dining.fast_food',
  'ロッテリア': 'dining.fast_food',
  'フレッシュネスバーガー': 'dining.fast_food',
  'ウェンディーズ': 'dining.fast_food',
  'サブウェイ': 'dining.fast_food',
  'ケンタッキーフライドチキン': 'dining.fast_food',
  'ケンタッキー': 'dining.fast_food',
  'KFCジャパン': 'dining.fast_food',
  'ドミノ・ピザ': 'dining.delivery',
  'ピザハット': 'dining.delivery',
  'ピザーラ': 'dining.delivery',
  'ウーバーイーツ': 'dining.delivery',
  'デリバリー': 'dining.delivery',
  'セブン-イレブン': 'convenience_store',
  'セブンイレブン': 'convenience_store',
  'ローソン': 'convenience_store',
  'ファミリーマート': 'convenience_store',
  'ミニストップ': 'convenience_store',
  'デイリーヤマザキ': 'convenience_store',
  'ポプラ': 'convenience_store',
  'イオン': 'grocery.supermarket',
  'イオンモール': 'grocery.supermarket',
  'イトーヨーカドー': 'grocery.supermarket',
  'ヨーカドー': 'grocery.supermarket',
  'ライフ': 'grocery.supermarket',
  'サミット': 'grocery.supermarket',
  'ヨークマート': 'grocery.supermarket',
  'オーケーストア': 'grocery.supermarket',
  'マルエツ': 'grocery.supermarket',
  'フードワン': 'grocery.supermarket',
  'ダイエー': 'grocery.supermarket',
  'ユニー': 'grocery.supermarket',
  'ピアゴ': 'grocery.supermarket',
  'ビッグカメラ': 'offline_shopping',
  'ヨドバシカメラ': 'offline_shopping',
  'エディオン': 'offline_shopping',
  'ケーズデンキ': 'offline_shopping',
  'ヤマダ電機': 'offline_shopping',
  'コジマ電気': 'offline_shopping',
  'ニトリ': 'offline_shopping',
  'ユニクロ': 'online_shopping.fashion',
  'ジーユー': 'online_shopping.fashion',
  'しまむら': 'online_shopping.fashion',
  'ライトオン': 'online_shopping.fashion',
  'アダストリア': 'online_shopping.fashion',
  'スシロー': 'dining.restaurant',
  'くら寿司': 'dining.restaurant',
  'はま寿司': 'dining.restaurant',
  'かっぱ寿司': 'dining.restaurant',
  '吉野家': 'dining.restaurant',
  'すき家': 'dining.restaurant',
  '松屋': 'dining.restaurant',
  'なか卯': 'dining.restaurant',
  'てんや': 'dining.restaurant',
  'やよい軒': 'dining.restaurant',
  'デニーズ': 'dining.restaurant',
  'ガスト': 'dining.restaurant',
  'バーミヤン': 'dining.restaurant',
  'ジョイフル': 'dining.restaurant',
  'ロイヤルホスト': 'dining.restaurant',
  'サイゼリヤ': 'dining.restaurant',
  'ドラッグストア': 'medical.pharmacy',
  'マツモトキヨシ': 'medical.pharmacy',
  'ツルハドラッグ': 'medical.pharmacy',
  'ウエルシア': 'medical.pharmacy',
  'スギ薬局': 'medical.pharmacy',
  'カワチ薬品': 'medical.pharmacy',
  'ダイコクドラッグ': 'medical.pharmacy',
  'コスモス薬品': 'medical.pharmacy',
  'クリエイトSD': 'medical.pharmacy',
  'JR東日本': 'public_transit.subway',
  'JR西日本': 'public_transit.subway',
  'JR東海': 'public_transit.subway',
  'JR九州': 'public_transit.subway',
  'JR北海道': 'public_transit.subway',
  '東京メトロ': 'public_transit.subway',
  '都営地下鉄': 'public_transit.subway',
  '阪急電鉄': 'public_transit.subway',
  '近鉄': 'public_transit.subway',
  '東急電鉄': 'public_transit.subway',
  '西武鉄道': 'public_transit.subway',
  '京急電鉄': 'public_transit.subway',
  '南海電鉄': 'public_transit.subway',
  '名鉄': 'public_transit.subway',
  '日本航空': 'travel.airline',
  '全日本空輸': 'travel.airline',
  'スカイマーク': 'travel.airline',
  'ピーチ': 'travel.airline',
  'ジェットスター': 'travel.airline',
  'エアドゥ': 'travel.airline',
  'ソラシドエア': 'travel.airline',
  'ANAホールディングス': 'travel.airline',
  'ホテル': 'travel.hotel',
  '旅館': 'travel.hotel',
  'じゃらん': 'travel.hotel',
  '楽天トラベル': 'travel.hotel',
  '一休コム': 'travel.hotel',
  'アマゾン': 'online_shopping',
  '楽天': 'online_shopping',
  '楽天市場': 'online_shopping',
  'Yahoo!ショッピング': 'online_shopping',
  'ヤフーショッピング': 'online_shopping',
  'メルカリ': 'online_shopping',
  'ラクマ': 'online_shopping',
  'Zozotown': 'online_shopping.fashion',
  'ゾゾタウン': 'online_shopping.fashion',
  'Netflix ジャパン': 'entertainment.streaming',
  'アマゾンプライム': 'entertainment.streaming',
  'Hulu JP': 'entertainment.streaming',
  'U-NEXT': 'entertainment.streaming',
  'Dアニメストア': 'entertainment.streaming',
  'ニコニコ動画': 'entertainment.streaming',
  'ABEMAプレミアム': 'entertainment.streaming',
  'Spotify ジャパン': 'entertainment.streaming',
  'Apple Music JP': 'entertainment.streaming',

  // Japan romanized
  'YOSHINOYA': 'dining.restaurant',
  'SUKIYA': 'dining.restaurant',
  'MATSUYA': 'dining.restaurant',
  'NAKAU': 'dining.restaurant',
  'SUSHIRO': 'dining.restaurant',
  'KURA SUSHI': 'dining.restaurant',
  'HAMA SUSHI': 'dining.restaurant',
  'KAPPA SUSHI': 'dining.restaurant',
  'DENNY S JP': 'dining.restaurant',
  'GUSTO': 'dining.restaurant',
  'BAMIYAN': 'dining.restaurant',
  'ROYAL HOST': 'dining.restaurant',
  'SAIZERIYA': 'dining.restaurant',
  'JOYFULL': 'dining.restaurant',
  'MOS BURGER': 'dining.fast_food',
  'LOTTERIA JP': 'dining.fast_food',
  'FRESHNESS BURGER': 'dining.fast_food',
  'LAWSON': 'convenience_store',
  'FAMILY MART': 'convenience_store',
  'FAMILYMART': 'convenience_store',
  'AEON': 'grocery.supermarket',
  'AEON MALL JP': 'grocery.supermarket',
  'ITO YOKADO': 'grocery.supermarket',
  'BIC CAMERA': 'offline_shopping',
  'YODOBASHI CAMERA': 'offline_shopping',
  'EDION': 'offline_shopping',
  'YAMADA DENKI': 'offline_shopping',
  'KOJIMA': 'offline_shopping',
  'NITORI': 'offline_shopping',
  'GU': 'online_shopping.fashion',
  'SHIMAMURA': 'online_shopping.fashion',
  'MATSUMOTOKIYOSHI': 'medical.pharmacy',
  'TSURUHA DRUG': 'medical.pharmacy',
  'WELCIA': 'medical.pharmacy',
  'SUGI PHARMACY': 'medical.pharmacy',
  'JR EAST': 'public_transit.subway',
  'JR WEST': 'public_transit.subway',
  'JR CENTRAL': 'public_transit.subway',
  'JR KYUSHU': 'public_transit.subway',
  'TOKYO METRO': 'public_transit.subway',
  'TOEI SUBWAY': 'public_transit.subway',
  'HANKYU': 'public_transit.subway',
  'KINTETSU': 'public_transit.subway',
  'TOKYU': 'public_transit.subway',
  'SEIBU': 'public_transit.subway',
  'KEIKYU': 'public_transit.subway',
  'NANKAI': 'public_transit.subway',
  'MEITETSU': 'public_transit.subway',
  'ANA AIRLINES': 'travel.airline',
  'SKYMARK': 'travel.airline',
  'PEACH AVIATION': 'travel.airline',
  'JETSTAR JP': 'travel.airline',
  'AIRDO': 'travel.airline',
  'SOLASEED': 'travel.airline',
  'JALAN': 'travel.hotel',
  'RAKUTEN TRAVEL': 'travel.hotel',
  'IKYU': 'travel.hotel',
  'AMAZON JP': 'online_shopping',
  'RAKUTEN ICHIBA': 'online_shopping',
  'YAHOO SHOPPING JP': 'online_shopping',
  'MERCARI JP': 'online_shopping',
  'RAKUMA': 'online_shopping',
  'ZOZOTOWN': 'online_shopping.fashion',
  'UNEXT': 'entertainment.streaming',
  'NICONICO': 'entertainment.streaming',

  // China - native script
  '星巴克': 'dining.cafe',
  '瑞幸咖啡': 'dining.cafe',
  '麦当劳': 'dining.fast_food',
  '肯德基': 'dining.fast_food',
  '汉堡王': 'dining.fast_food',
  '必胜客': 'dining.delivery',
  '达美乐': 'dining.delivery',
  '美团外卖': 'dining.delivery',
  '饿了么': 'dining.delivery',
  '盒马鲜生': 'grocery.online_grocery',
  '叮咚买菜': 'grocery.online_grocery',
  '朴朴超市': 'grocery.online_grocery',
  '每日优鲜': 'grocery.online_grocery',
  '大润发': 'grocery.supermarket',
  '沃尔玛中国': 'grocery.supermarket',
  '家乐福中国': 'grocery.supermarket',
  '永辉超市': 'grocery.supermarket',
  '华润万家': 'grocery.supermarket',
  '物美超市': 'grocery.supermarket',
  '中百仓储': 'grocery.supermarket',
  '大商超市': 'grocery.supermarket',
  '步步高超市': 'grocery.supermarket',
  '全家便利店': 'convenience_store',
  '罗森便利': 'convenience_store',
  '7-11中国': 'convenience_store',
  '美宜佳': 'convenience_store',
  '淘宝': 'online_shopping',
  '天猫': 'online_shopping',
  '京东': 'online_shopping',
  '拼多多': 'online_shopping',
  '苏宁易购': 'online_shopping',
  '唯品会': 'online_shopping.fashion',
  '当当网': 'education.books',
  '得物App': 'online_shopping.fashion',
  '小红书': 'online_shopping',
  '网易严选': 'online_shopping',
  '字节跳动': 'entertainment',
  '抖音': 'entertainment',
  '快手': 'entertainment',
  '哔哩哔哩': 'entertainment.streaming',
  '爱奇艺': 'entertainment.streaming',
  '优酷': 'entertainment.streaming',
  '腾讯视频': 'entertainment.streaming',
  '网易云音乐': 'entertainment.streaming',
  'QQ音乐': 'entertainment.streaming',
  '酷狗音乐': 'entertainment.streaming',
  '微信支付': 'online_shopping',
  '支付宝': 'online_shopping',
  '滴滴出行': 'public_transit.taxi',
  '曹操出行': 'public_transit.taxi',
  '嘀嗒出行': 'public_transit.taxi',
  '高德打车': 'public_transit.taxi',
  '美团打车': 'public_transit.taxi',
  '北京地铁': 'public_transit.subway',
  '上海地铁': 'public_transit.subway',
  '广州地铁': 'public_transit.subway',
  '深圳地铁': 'public_transit.subway',
  '中国国际航空': 'travel.airline',
  '中国东方航空': 'travel.airline',
  '中国南方航空': 'travel.airline',
  '海南航空': 'travel.airline',
  '厦门航空': 'travel.airline',
  '川航': 'travel.airline',
  '深圳航空': 'travel.airline',
  '春秋航空': 'travel.airline',
  '吉祥航空': 'travel.airline',
  '西部航空': 'travel.airline',
  '携程旅行': 'travel.travel_agency',
  '去哪儿网': 'travel.travel_agency',
  '同程旅行': 'travel.travel_agency',
  '飞猪旅行': 'travel.travel_agency',
  '美团酒店': 'travel.hotel',
  '如家酒店': 'travel.hotel',
  '汉庭酒店': 'travel.hotel',
  '华住酒店': 'travel.hotel',
  '锦江酒店': 'travel.hotel',
  '格林豪泰': 'travel.hotel',
  '七天连锁': 'travel.hotel',
  '希尔顿中国': 'travel.hotel',
  '万豪中国': 'travel.hotel',
  '网易': 'online_shopping',
  '百度': 'subscription',
  '腾讯': 'entertainment',
  '阿里巴巴': 'online_shopping',

  // China romanized
  'ALIBABA COM': 'online_shopping',
  'TAOBAO': 'online_shopping',
  'TMALL': 'online_shopping',
  'JD COM': 'online_shopping',
  'JINGDONG': 'online_shopping',
  'PINDUODUO': 'online_shopping',
  'SUNING': 'online_shopping',
  'VIPSHOP': 'online_shopping.fashion',
  'DANGDANG': 'education.books',
  'TENCENT': 'entertainment',
  'NETEASE': 'entertainment',
  'BILIBILI': 'entertainment.streaming',
  'IQIYI': 'entertainment.streaming',
  'YOUKU': 'entertainment.streaming',
  'TENCENT VIDEO': 'entertainment.streaming',
  'MEITUAN': 'dining.delivery',
  'ELEME': 'dining.delivery',
  'HEMA FRESH': 'grocery.online_grocery',
  'DINGDONG MAICAI': 'grocery.online_grocery',
  'CHINA EASTERN AIRLINES': 'travel.airline',
  'CHINA SOUTHERN AIRLINES': 'travel.airline',
  'HAINAN AIRLINES': 'travel.airline',
  'SPRING AIRLINES': 'travel.airline',
  'LUCKY AIR': 'travel.airline',
  'QUNAR': 'travel.travel_agency',
  'FLIGGY': 'travel.travel_agency',
  'TONCHENG': 'travel.travel_agency',
  'HUAZHU': 'travel.hotel',
  'JINJIANG INN': 'travel.hotel',
  'HOME INN': 'travel.hotel',
  'HANTING': 'travel.hotel',
  'GREENLAND HOTEL': 'travel.hotel',
  'RUJIA': 'travel.hotel',
  'ATOUR HOTEL': 'travel.hotel',

  // Southeast Asia
  'SHOPEE': 'online_shopping',
  'SHOPEE PH': 'online_shopping',
  'SHOPEE MY': 'online_shopping',
  'LAZADA': 'online_shopping',
  'LAZADA SG': 'online_shopping',
  'TOKOPEDIA': 'online_shopping',
  'BUKALAPAK': 'online_shopping',
  'BLIBLI': 'online_shopping',
  'TIKI VN': 'online_shopping',
  'SENDO VN': 'online_shopping',
  'CAROUSELL': 'online_shopping',
  'GOJEK ID': 'public_transit.taxi',
  'OJEK ONLINE': 'public_transit.taxi',
  'GRAB SG': 'public_transit.taxi',
  'GRAB MY': 'public_transit.taxi',
  'GRAB PH': 'public_transit.taxi',
  'GRAB ID': 'public_transit.taxi',
  'GRAB TH': 'public_transit.taxi',
  'MAXIM': 'public_transit.taxi',
  'INDRIVER': 'public_transit.taxi',
  'FOODPANDA SG': 'dining.delivery',
  'FOODPANDA MY': 'dining.delivery',
  'FOODPANDA PH': 'dining.delivery',
  'GRABFOOD': 'dining.delivery',
  'GOFOOD': 'dining.delivery',
  'LINE MAN': 'dining.delivery',
  'SHOPEEFOOD': 'dining.delivery',
  'GRAB PAY': 'online_shopping',
  'GOPAY': 'online_shopping',
  'OVO': 'online_shopping',
  'DANA WALLET': 'online_shopping',
  'TOUCH N GO': 'online_shopping',
  'SINGTEL': 'telecom',
  'STARHUB': 'telecom',
  'M1 TELECOM': 'telecom',
  'CELCOM': 'telecom',
  'MAXIS': 'telecom',
  'DIGI TELCO': 'telecom',
  'GLOBE TELECOM': 'telecom',
  'SMART COMM': 'telecom',
  'DITO TELECOM': 'telecom',
  'VIETTEL': 'telecom',
  'VINAPHONE': 'telecom',
  'MOBIFONE': 'telecom',
  'TRUE MOVE': 'telecom',
  'DTAC': 'telecom',
  'AIS THAILAND': 'telecom',
  'TELKOMSEL': 'telecom',
  'XL AXIATA': 'telecom',
  'INDOSAT': 'telecom',
  'THAI AIRWAYS TH': 'travel.airline',
  'THAI LION AIR': 'travel.airline',
  'NOKAIR': 'travel.airline',
  'BANGKOK AIRWAYS': 'travel.airline',
  'VIETNAM AIRLINES VN': 'travel.airline',
  'VIETJET AIR': 'travel.airline',
  'BAMBOO AIRWAYS': 'travel.airline',
  'LION AIR ID': 'travel.airline',
  'BATIK AIR ID': 'travel.airline',
  'CITILINK': 'travel.airline',
  'WINGS AIR': 'travel.airline',
  'PHILIPPINE AIR': 'travel.airline',
  'CEBU PAC': 'travel.airline',
  'PAL EXPRESS': 'travel.airline',
  'MALAYSIA AIR': 'travel.airline',
  'FIREFLY': 'travel.airline',
  'SINGAPORE AIR': 'travel.airline',
  'SCOOT AIRLINES': 'travel.airline',
  'SILKAIR': 'travel.airline',
  'MRT SINGAPORE': 'public_transit.subway',
  'SMRT TRAINS': 'public_transit.subway',
  'LRT SG': 'public_transit.subway',
  'BTS SKYTRAIN': 'public_transit.subway',
  'MRT BANGKOK': 'public_transit.subway',
  'MRT KL': 'public_transit.subway',
  'LRT KL': 'public_transit.subway',
  'MRT TAIPEI': 'public_transit.subway',
  'BRT TAIPEI': 'public_transit.subway',
  'JAKARTA MRT': 'public_transit.subway',
  'COMMUTER LINE': 'public_transit.subway',
  'AEON MY': 'grocery.supermarket',
  'GIANT MY': 'grocery.supermarket',
  'TESCO MY': 'grocery.supermarket',
  'COLD STORAGE SG': 'grocery.supermarket',
  'NTUC FAIRPRICE': 'grocery.supermarket',
  'SHENG SIONG': 'grocery.supermarket',
  'JAYA GROCER': 'grocery.supermarket',
  'VILLAGE GROCER': 'grocery.supermarket',
  'ROBINSONS': 'offline_shopping',
  'SM SUPERMALLS': 'offline_shopping',
  'AYALA MALLS': 'offline_shopping',
  'SM MARKETS': 'grocery.supermarket',
  'ROBINSONS SUPERMARKET': 'grocery.supermarket',
  'PUREGOLD': 'grocery.supermarket',
  'MERCURY DRUG PH': 'medical.pharmacy',
  'ROSE PHARMACY': 'medical.pharmacy',
  'GUARDIAN SG': 'medical.pharmacy',
  'GUARDIAN MY': 'medical.pharmacy',
  'WATSONS SG': 'medical.pharmacy',
  'WATSONS MY': 'medical.pharmacy',
  'WATSONS TH': 'medical.pharmacy',
  'WATSONS PH': 'medical.pharmacy',
  'WATSONS HK': 'medical.pharmacy',
  'WATSON S CHINA': 'medical.pharmacy',

  // Korea - additional transport & misc
  'TMONEY': 'public_transit',
  'CASHBEE': 'public_transit',
  'SEOUL BUS': 'public_transit.bus',
  'GYEONGGI BUS': 'public_transit.bus',
  'INCHEON BUS': 'public_transit.bus',
  'BUSAN BUS': 'public_transit.bus',
  'DAEJEON BUS': 'public_transit.bus',
  'GWANGJU BUS': 'public_transit.bus',
  'KAKAO BUS': 'public_transit.bus',
  'NAVER MAPS': 'public_transit',
  'KAKAO MAP': 'public_transit',
  'TMAP': 'public_transit',
  'INCHEON AIRPORT': 'travel',
  'GIMPO AIRPORT': 'travel',
  'GIMHAE AIRPORT': 'travel',
  'AIRPORT LIMOUSINE': 'public_transit.bus',
  'AREX': 'public_transit.subway',
  'LG CNS': 'subscription',
  'SK HOLDINGS': 'subscription',
  'SK INNOVATION': 'subscription',
  'POSCO': 'offline_shopping',
  'SAMSUNG CARD': 'offline_shopping',
  'HYUNDAI CARD': 'offline_shopping',
  'KB CARD': 'offline_shopping',
  'SHINHAN CARD': 'offline_shopping',
  'LOTTE CARD': 'offline_shopping',
  'NH CARD': 'offline_shopping',
  'WOORI CARD': 'offline_shopping',
  'HANA CARD': 'offline_shopping',
  'BC CARD': 'offline_shopping',
  'KAKAO BANK': 'online_shopping',
  'K BANK': 'online_shopping',
  'TOSS': 'online_shopping',
  'TOSS BANK': 'online_shopping',
  'NAVER FINANCIAL CORP': 'online_shopping',
  'NAVER PAY': 'online_shopping',
  'SAMSUNG PAY': 'online_shopping',
  'LG PAY': 'online_shopping',
  'PAYCO': 'online_shopping',
  'ZERO PAY': 'online_shopping',
  'ZEROPAY': 'online_shopping',
  'GS PAY': 'online_shopping',
  'SSGPAY': 'online_shopping',
  'SSG PAY': 'online_shopping',
  'HAPPY MONEY': 'online_shopping',
  'CULTURELAND': 'entertainment',
  'BOOK CULTURE': 'education.books',
  'MELON': 'entertainment.streaming',
  'BUGS MUSIC': 'entertainment.streaming',
  'FLO MUSIC': 'entertainment.streaming',
  'VIBE MUSIC': 'entertainment.streaming',
  'NAVER SERIES': 'entertainment',
  'KAKAO WEBTOON': 'entertainment',
  'TVING CO': 'entertainment.streaming',
  'WAVVE CORP': 'entertainment.streaming',
  'WATCHA INC': 'entertainment.streaming',
  'COUPANG PLAY INC': 'entertainment.streaming',
  'SEEZN': 'entertainment.streaming',
  'NAVER WHALE': 'subscription',
  'NAVER CLOUD': 'subscription',
  'KAKAO CLOUD': 'subscription',
  'NHN CLOUD': 'subscription',
  'GABIA': 'subscription',
  'CAFE24': 'subscription',
  'GODADDY KR': 'subscription',
  'HOSTING KR': 'subscription',
  'IWINV': 'subscription',
  'NAVER STUDIO': 'subscription',
  'KAKAO ENTERPRISE': 'subscription',
  'SK BROADBAND': 'telecom',
  'LG HELLOVISION': 'telecom',
  'KT GIGA INTERNET': 'telecom',
  'SK TELINK': 'telecom',
  'MVNO': 'telecom',
  'FREETELECOM': 'telecom',
  'U MOBILE': 'telecom',
  'HELLO MOBILE': 'telecom',
  'TING MOBILE': 'telecom',

  // Parking Korea
  'KAKAO PARKING': 'transportation.parking',
  'NAVER PARKING': 'transportation.parking',
  'MOORING PARKING': 'transportation.parking',
  'IPARK PARKING': 'transportation.parking',
  'CITY PARKING': 'transportation.parking',
  'APARK': 'transportation.parking',

  // EV Charging Korea
  'CHARGEPOINT KR': 'transportation',
  'HYUNDAI MOTORSTUDIO': 'transportation',
  'HYUNDAI EV': 'transportation',
  'TESLA KOREA': 'transportation',
  'TESLA': 'transportation',
  'EVERON': 'transportation',
  'CHARGESPOT': 'transportation',
  'SKE EV': 'transportation',
  'EVAR CHARGING': 'transportation',
  'KEPCO EV': 'transportation',

  // Additional global tech
  'LINKEDIN': 'subscription',
  'LINKEDIN PREMIUM': 'subscription',
  'TWITTER': 'subscription',
  'X CORP': 'subscription',
  'META PLATFORMS': 'subscription',
  'META ADS': 'subscription',
  'FACEBOOK ADS': 'subscription',
  'INSTAGRAM ADS': 'subscription',
  'SNAP INC': 'subscription',
  'SNAPCHAT PLUS': 'subscription',
  'PINTEREST': 'subscription',
  'REDDIT': 'subscription',
  'DISCORD': 'subscription',
  'DISCORD NITRO': 'subscription',
  'PATREON': 'subscription',
  'SUBSTACK': 'subscription',
  'MEDIUM': 'subscription',
  'SQUARESPACE': 'subscription',
  'WIX': 'subscription',
  'WORDPRESS COM': 'subscription',
  'NAMECHEAP': 'subscription',
  'SITEGROUND': 'subscription',
  'HOSTGATOR': 'subscription',
  'BLUEHOST': 'subscription',
  'CONTABO': 'subscription',
  'VULTR': 'subscription',
  'ORACLE CLOUD': 'subscription',
  'IBM CLOUD': 'subscription',
  'ELASTIC CLOUD': 'subscription',
  'DATADOG': 'subscription',
  'NEW RELIC': 'subscription',
  'PAGERDUTY': 'subscription',
  'SPLUNK': 'subscription',
  'ZENDESK': 'subscription',
  'FRESHDESK': 'subscription',
  'INTERCOM': 'subscription',
  'MONDAY COM': 'subscription',
  'ASANA': 'subscription',
  'BASECAMP': 'subscription',
  'CLICKUP': 'subscription',
  'TODOIST': 'subscription',
  'THINGS 3': 'subscription',

  // Food & Dining global
  'JUST EAT UK': 'dining.delivery',
  'DELIVEROO UK': 'dining.delivery',
  'WOLT': 'dining.delivery',
  'GLOVO': 'dining.delivery',
  'BOLT FOOD': 'dining.delivery',
  'UBER EATS EU': 'dining.delivery',
  'STUFFLE': 'dining.delivery',
  'LIEFERANDO': 'dining.delivery',

  // Insurance global
  'ALLIANZ': 'insurance',
  'AXA': 'insurance',
  'PRUDENTIAL': 'insurance',
  'MANULIFE': 'insurance',
  'AIA INSURANCE': 'insurance',
  'CIGNA': 'insurance',
  'AETNA': 'insurance',
  'METLIFE': 'insurance',
  'ZURICH INSURANCE': 'insurance',
  'GENERALI': 'insurance',
  'AVIVA': 'insurance',
  'ZURICH': 'insurance',

  // Education global
  'COURSERA': 'education',
  'UDEMY': 'education',
  'EDUREKA': 'education',
  'PLURALSIGHT': 'education',
  'LINKEDIN LEARNING': 'education',
  'DUOLINGO': 'education',
  'DUOLINGO PLUS': 'education',
  'KHAN ACADEMY': 'education',
  'CHEGG': 'education',
  'SKILLSHARE': 'education',
  'MASTERCLASS': 'education',
  'BRILLIANT ORG': 'education',
  'ROSETTA STONE': 'education',
  'BABBEL': 'education',
  'SPEAK APP': 'education',
  'CREATIE': 'education',
  'LEETCODE': 'education',

  // Health / Fitness global
  'PELOTON': 'subscription',
  'CLASSPASS': 'subscription',
  'HEADSPACE': 'subscription',
  'CALM APP': 'subscription',
  'NOOM': 'subscription',
  'MYFITNESSPAL': 'subscription',
  'STRAVA': 'subscription',
  'ZWIFT': 'subscription',
  'FITBIT': 'offline_shopping',
  'GARMIN': 'offline_shopping',
};
