/** Build a Map from category IDs (including dot-notation subcategory keys)
 *  to their Korean labels. Used by the analyzer, store, and CardDetail
 *  to avoid duplicating the Map construction logic (C36-03). */

import type { CategoryNode } from './cards.js';

export function buildCategoryLabelMap(nodes: CategoryNode[]): Map<string, string> {
  const labels = new Map<string, string>();
  for (const node of nodes) {
    labels.set(node.id, node.labelKo);
    if (node.subcategories) {
      for (const sub of node.subcategories) {
        labels.set(sub.id, sub.labelKo);
        labels.set(`${node.id}.${sub.id}`, sub.labelKo);
      }
    }
  }
  return labels;
}

/** Auto-generated fallback labels from canonical categories.yaml.
 *  Regenerated by scripts/build-json.ts — do not edit manually. */
export { FALLBACK_CATEGORY_LABELS } from './category-labels-fallback.js';
